version: '3'

services:
  web:
    container_name: ecommerce
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://root:12345@db:5433/postgres
      PORT: 3002
      TOKEN_SECRET: 123
      URL_BASE: https://myown-domain.google.com
    build: .
    ports:
      - "7000:7000"
    links:
      - db


  db:
    container_name: postgresdb
    image: postgres:14.1-alpine
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
    command: -p 5433
    expose:
      - 5433